import React from 'react';
import { Calendar, Globe, Sparkles } from 'lucide-react';
import Link from 'next/link';

export function ReportThankYouCard() {
 return (
 <div className="pdf-page-break-avoid w-full max-w-full mx-auto my-8 p-6 sm:p-8 bg-gradient-to-b from-amber-500/15 via-amber-100/30 to-amber-500/15 border-2 border-amber-600 rounded-3xl text-center space-y-6 shadow-xl relative overflow-hidden">
 
 {/* Top Decorative Gold Accent Bar */}
 <div className="absolute top-0 left-0 right-0 h-2 bg-gradient-to-r from-amber-400 via-amber-600 to-amber-400" />
 
 {/* Thank You Header */}
 <div className="space-y-1.5 pt-2">
 <span className="text-2xl sm:text-3xl tracking-widest text-amber-600 ">✦ ✨ ✦</span>
 <h2 className="font-sans text-3xl sm:text-4xl font-extrabold text-amber-950 tracking-wide">
 Thank You
 </h2>
 <div className="w-24 h-1 bg-amber-500 mx-auto rounded-full" />
 </div>

 {/* Generated by & Website Grid */}
 <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 max-w-2xl mx-auto pt-2">
 
 {/* Generated By */}
 <div className="p-4 bg-white/90 rounded-2xl border border-amber-300 shadow-sm flex flex-col items-center justify-center space-y-1">
 <span className="text-[11px] uppercase font-bold tracking-widest text-amber-800 font-mono">
 Generated By
 </span>
 <span className="font-sans font-extrabold text-xl sm:text-2xl text-amber-950 ">
 OM Astrology AMC
 </span>
 </div>

 {/* Website */}
 <div className="p-4 bg-white/90 rounded-2xl border border-amber-300 shadow-sm flex flex-col items-center justify-center space-y-1">
 <span className="text-[11px] uppercase font-bold tracking-widest text-amber-800 font-mono flex items-center gap-1.5">
 <Globe className="w-3.5 h-3.5 text-amber-600 " /> Website
 </span>
 <a 
 href="https://www.omastrologyamc.com/" 
 target="_blank" 
 rel="noopener noreferrer"
 className="font-sans font-bold text-base sm:text-lg text-amber-700 hover:underline"
 >
 www.omastrologyamc.com
 </a>
 </div>

 </div>

 {/* Consultation Banner / CTA (Inside same container below Generated By / Website) */}
 {/* 
 <div className="p-6 bg-[#fffef7] border-2 border-amber-300 rounded-2xl shadow-md max-w-2xl mx-auto space-y-3 text-center mt-8">
 <div className="w-10 h-10 rounded-full bg-amber-100 border border-amber-300 flex items-center justify-center mx-auto text-amber-800 ">
 <Sparkles className="w-5 h-5" />
 </div>
 <h3 className="font-serif text-xl sm:text-2xl font-bold text-amber-950 ">
 Book Your Complete Personal Life Reading
 </h3>
 <p className="text-xs sm:text-sm text-neutral-700 max-w-lg mx-auto leading-relaxed">
 Speak directly with certified Vedic Astrologers & Master Numerologists to decode your planetary remedies and future timeline.
 </p>
 <div className="pt-2 flex justify-center">
 <Link 
 href="/appointments"
 className="px-6 py-2.5 bg-amber-500 hover:bg-amber-600 text-gray-900 font-bold rounded-full text-xs sm:text-sm shadow-md transition-all transform hover:scale-105 flex items-center gap-2 border border-amber-400"
 >
 <Calendar className="w-4 h-4" /> Book 1-on-1 Appointment →
 </Link>
 </div>
 </div>
 */}

 </div>
 );
}
