// Comprehensive Nakshatra Dataset & Analysis Helper for 27 Nakshatras

export interface NakshatraDetail {
 name: string;
 ruler: string;
 deity: string;
 symbol: string;
 animal: string;
 gana: 'Deva' | 'Manushya' | 'Rakshasa';
 nadi: 'Adi' | 'Madhya' | 'Antya';
 yoni: string;
 nature: string;
 characteristics: string;
 career: string;
 marriage: string;
 compatibility: string[];
}

export const NAKSHATRA_DATASET: Record<string, NakshatraDetail> = {
 Ashwini: {
 name: 'Ashwini',
 ruler: 'Ketu',
 deity: 'Ashwini Kumaras (Divine Physicians)',
 symbol: "Horse's Head",
 animal: 'Male Horse',
 gana: 'Deva',
 nadi: 'Adi',
 yoni: 'Horse',
 nature: 'Light & Swift (Kshipra)',
 characteristics: 'Pioneering, energetic, fast-moving, courageous, spontaneous, passionate about healing.',
 career: 'Medicine, surgery, sports, military, aviation, entrepreneurship, emergency services.',
 marriage: 'Seeks quick action and freedom in relationships. Compatible with loyal and dynamic partners.',
 compatibility: ['Bharani', 'Rohini', 'Pushya', 'Swati']
 },
 Bharani: {
 name: 'Bharani',
 ruler: 'Venus',
 deity: 'Yama (God of Death & Justice)',
 symbol: 'Yoni (Female Reproductive Organ)',
 animal: 'Elephant',
 gana: 'Manushya',
 nadi: 'Madhya',
 yoni: 'Elephant',
 nature: 'Fierce & Severe (Ugra)',
 characteristics: 'Transformative, creative, intense, moralistic, protective, strong-willed, determined.',
 career: 'Creative arts, gynecology, hospitality, executive management, law, judicial services.',
 marriage: 'Passionate and deeply loyal, values intense commitment and emotional honesty.',
 compatibility: ['Ashwini', 'Krittika', 'Revati', 'Hasta']
 },
 Krittika: {
 name: 'Krittika',
 ruler: 'Sun',
 deity: 'Agni (God of Fire)',
 symbol: 'Blade / Flame / Razor',
 animal: 'Female Sheep (Goat)',
 gana: 'Rakshasa',
 nadi: 'Antya',
 yoni: 'Sheep',
 nature: 'Mixed & Sharp (Misra)',
 characteristics: 'Purifying, direct, sharp intelligence, protective motherly instincts, fiery temperament.',
 career: 'Military leadership, culinary arts, metallurgy, engineering, politics, criticism, surgery.',
 marriage: 'High expectations in partnership; fiercely protective of home and family.',
 compatibility: ['Bharani', 'Rohini', 'Uttara Phalguni', 'Dhanishta']
 },
 Rohini: {
 name: 'Rohini',
 ruler: 'Moon',
 deity: 'Brahma (The Creator)',
 symbol: 'Chariot / Banyan Tree',
 animal: 'Cobra / Serpent',
 gana: 'Manushya',
 nadi: 'Antya',
 yoni: 'Serpent',
 nature: 'Fixed & Steady (Sthira)',
 characteristics: 'Charming, artistic, sensual, growth-oriented, persuasive, material abundance, magnetic personality.',
 career: 'Fashion design, acting, music, luxury products, agriculture, real estate, hospitality.',
 marriage: 'Deeply romantic and devoted; thrives in harmonious, aesthetically pleasing relationships.',
 compatibility: ['Mrigashira', 'Ashwini', 'Swati', 'Anuradha']
 },
 Mrigashira: {
 name: 'Mrigashira',
 ruler: 'Mars',
 deity: 'Soma (Moon God)',
 symbol: "Deer's Head",
 animal: 'Female Serpent',
 gana: 'Deva',
 nadi: 'Madhya',
 yoni: 'Serpent',
 nature: 'Soft & Tender (Mridu)',
 characteristics: 'Curious, investigative, perpetual seeker, gentle, highly intelligent, adaptable, restless.',
 career: 'Research, journalism, travel guide, software development, music, writing, archaeology.',
 marriage: 'Requires mental stimulation and clear communication in domestic life.',
 compatibility: ['Rohini', 'Ardra', 'Chitra', 'Dhanishta']
 },
 Ardra: {
 name: 'Ardra',
 ruler: 'Rahu',
 deity: 'Rudra (Storm God)',
 symbol: 'Teardrop / Diamond',
 animal: 'Female Dog',
 gana: 'Manushya',
 nadi: 'Adi',
 yoni: 'Dog',
 nature: 'Sharp & Dreadful (Tikshna)',
 characteristics: 'Analytical, emotional clarity through struggle, transformational insight, hardworking, sharp tongue.',
 career: 'Data science, electronic engineering, weather forecasting, psychology, investigative journalism.',
 marriage: 'Deeply sincere after emotional breakthroughs; needs understanding and empathetic partner.',
 compatibility: ['Mrigashira', 'Punarvasu', 'Swati', 'Shatabhisha']
 },
 Punarvasu: {
 name: 'Punarvasu',
 ruler: 'Jupiter',
 deity: 'Aditi (Mother of Gods)',
 symbol: 'Quiver of Arrows',
 animal: 'Female Cat',
 gana: 'Deva',
 nadi: 'Adi',
 yoni: 'Cat',
 nature: 'Movable & Renewable (Chara)',
 characteristics: 'Optimistic, forgiving, generous, resilient, spiritual wisdom, restorer of peace.',
 career: 'Teaching, counseling, astrology, philosophy, civil service, publishing, aviation.',
 marriage: 'Warm, nurturing, and traditional values in family life; brings peace to household.',
 compatibility: ['Pushya', 'Ashlesha', 'Ardra', 'Vishakha']
 },
 Pushya: {
 name: 'Pushya',
 ruler: 'Saturn',
 deity: 'Brihaspati (Guru of Gods)',
 symbol: 'Cow’s Udder / Lotus / Arrow',
 animal: 'Male Ram',
 gana: 'Deva',
 nadi: 'Madhya',
 yoni: 'Ram',
 nature: 'Light & Swift (Kshipra)',
 characteristics: 'Nurturing, highly auspicious, lawful, patient, spiritual pillar, benevolent, dutiful.',
 career: 'Government administration, law, religious leadership, education, dairy industry, philanthropy.',
 marriage: 'Extremely committed and protective spouse; prioritizes duty and long-term security.',
 compatibility: ['Punarvasu', 'Ashlesha', 'Uttara Phalguni', 'Anuradha']
 },
 Ashlesha: {
 name: 'Ashlesha',
 ruler: 'Mercury',
 deity: 'Nagas (Serpent Deities)',
 symbol: 'Coiled Serpent',
 animal: 'Male Cat',
 gana: 'Rakshasa',
 nadi: 'Antya',
 yoni: 'Cat',
 nature: 'Sharp & Dreadful (Tikshna)',
 characteristics: 'Intuitively perceptive, strategic, hypnotic charm, protective of loved ones, secret knowledge.',
 career: 'Psychology, pharmacology, diplomacy, intelligence agencies, chemistry, research.',
 marriage: 'Intense attachment; needs a partner who respects intuition and non-verbal understanding.',
 compatibility: ['Pushya', 'Punarvasu', 'Jyeshta', 'Revati']
 },
 Magha: {
 name: 'Magha',
 ruler: 'Ketu',
 deity: 'Pitris (Ancestral Spirits)',
 symbol: 'Royal Throne',
 animal: 'Male Rat',
 gana: 'Rakshasa',
 nadi: 'Antya',
 yoni: 'Rat',
 nature: 'Fierce & Severe (Ugra)',
 characteristics: 'Regal demeanor, respectful of lineage, natural authority, generous leader, noble pride.',
 career: 'Politics, corporate executive, heritage management, archaeology, government leadership.',
 marriage: 'Expects respect and dignity in marital bond; deeply honors family traditions.',
 compatibility: ['Purva Phalguni', 'Uttara Phalguni', 'Ashwini', 'Mula']
 },
 'Purva Phalguni': {
 name: 'Purva Phalguni',
 ruler: 'Venus',
 deity: 'Bhaga (God of Delight & Fortune)',
 symbol: 'Front Legs of Hammock / Bed',
 animal: 'Female Rat',
 gana: 'Manushya',
 nadi: 'Madhya',
 yoni: 'Rat',
 nature: 'Fierce & Severe (Ugra)',
 characteristics: 'Joyful, romantic, social, lover of arts and leisure, charismatic, relaxed attitude.',
 career: 'Entertainment, romance author, event management, beauty industry, interior design, music.',
 marriage: 'Thrives on romance, luxury, and affectionate partnership; deeply loving bond.',
 compatibility: ['Magha', 'Uttara Phalguni', 'Hasta', 'Bharani']
 },
 'Uttara Phalguni': {
 name: 'Uttara Phalguni',
 ruler: 'Sun',
 deity: 'Aryaman (God of Patronage & Contracts)',
 symbol: 'Back Legs of Bed / Fig Tree',
 animal: 'Bull',
 gana: 'Manushya',
 nadi: 'Adi',
 yoni: 'Bull',
 nature: 'Fixed & Steady (Sthira)',
 characteristics: 'Reliable, honorable, protective guardian, generous benefactor, committed friend.',
 career: 'Public relations, social work, jurisprudence, international trade, philanthropy, diplomacy.',
 marriage: 'Strong emphasis on marital contracts, mutual support, and honorable living.',
 compatibility: ['Magha', 'Purva Phalguni', 'Hasta', 'Anuradha']
 },
 Hasta: {
 name: 'Hasta',
 ruler: 'Moon',
 deity: 'Savitar (Solar Deity of Sunrise)',
 symbol: 'Open Hand / Fist',
 animal: 'Female Buffalo',
 gana: 'Deva',
 nadi: 'Adi',
 yoni: 'Buffalo',
 nature: 'Light & Swift (Kshipra)',
 characteristics: 'Skilled hands, witty, resourceful, industrious, dexterous, persuasive speech.',
 career: 'Handicrafts, surgery, magic, comedy, accounting, massage therapy, jewelry craft.',
 marriage: 'Helpful and supportive partner; brings practical joy and humor into domestic life.',
 compatibility: ['Chitra', 'Swati', 'Uttara Phalguni', 'Bharani']
 },
 Chitra: {
 name: 'Chitra',
 ruler: 'Mars',
 deity: 'Vishwakarma (Celestial Architect)',
 symbol: 'Bright Jewel / Pearl',
 animal: 'Female Tiger',
 gana: 'Rakshasa',
 nadi: 'Madhya',
 yoni: 'Tiger',
 nature: 'Soft & Tender (Mridu)',
 characteristics: 'Artistic brilliance, elegant aesthetics, architect of forms, structural perfectionist.',
 career: 'Architecture, graphic design, fashion, mechanical engineering, gems, photography.',
 marriage: 'Seeks visually pleasing and intellectually engaging union; highly independent.',
 compatibility: ['Hasta', 'Swati', 'Vishakha', 'Mrigashira']
 },
 Swati: {
 name: 'Swati',
 ruler: 'Rahu',
 deity: 'Vayu (Wind God)',
 symbol: 'Single Blade of Grass / Coral',
 animal: 'Male Buffalo',
 gana: 'Deva',
 nadi: 'Antya',
 yoni: 'Buffalo',
 nature: 'Movable & Flexible (Chara)',
 characteristics: 'Independent, adaptable, diplomatic, lover of freedom, business acumen, intuitive.',
 career: 'International business, trade, diplomacy, public speaking, aviation, music, law.',
 marriage: 'Values personal freedom and equality in marriage; gentle and communicative spouse.',
 compatibility: ['Hasta', 'Chitra', 'Ardra', 'Shatabhisha']
 },
 Vishakha: {
 name: 'Vishakha',
 ruler: 'Jupiter',
 deity: 'Indra & Agni (Chiefs of Devas)',
 symbol: 'Decorated Archway / Potter’s Wheel',
 animal: 'Male Tiger',
 gana: 'Rakshasa',
 nadi: 'Antya',
 yoni: 'Tiger',
 nature: 'Mixed & Sharp (Misra)',
 characteristics: 'Single-minded focus, goal-oriented, triumphant ambition, passionate determination.',
 career: 'Politics, competitive sports, trial law, executive leadership, sales targets, research.',
 marriage: 'Passionate and goal-oriented; demands mutual growth and shared goals with spouse.',
 compatibility: ['Anuradha', 'Punarvasu', 'Chitra', 'Uttara Bhadrapada']
 },
 Anuradha: {
 name: 'Anuradha',
 ruler: 'Saturn',
 deity: 'Mitra (God of Divine Friendship)',
 symbol: 'Triumphal Archway / Lotus',
 animal: 'Female Deer',
 gana: 'Deva',
 nadi: 'Madhya',
 yoni: 'Deer',
 nature: 'Soft & Tender (Mridu)',
 characteristics: 'Fosters deep friendships, organizational mastermind, spiritual devotion, global mindset.',
 career: 'Event coordination, international relations, music bands, organizational psychology, travel.',
 marriage: 'Deeply loyal and romantic; overcomes obstacles through faith and devotion to family.',
 compatibility: ['Vishakha', 'Jyeshta', 'Pushya', 'Rohini']
 },
 Jyeshta: {
 name: 'Jyeshta',
 ruler: 'Mercury',
 deity: 'Indra (King of Devas)',
 symbol: 'Circular Amulet / Earring',
 animal: 'Male Deer',
 gana: 'Rakshasa',
 nadi: 'Adi',
 yoni: 'Deer',
 nature: 'Sharp & Dreadful (Tikshna)',
 characteristics: 'Elderly wisdom, protective leader, courageous defender, intuitive occult mastery.',
 career: 'Military command, police force, executive management, occult sciences, auditing.',
 marriage: 'Protective of spouse; demands trust, honor, and mutual respect in domestic sphere.',
 compatibility: ['Anuradha', 'Ashlesha', 'Mula', 'Revati']
 },
 Mula: {
 name: 'Mula',
 ruler: 'Ketu',
 deity: 'Nirriti (Goddess of Dissolution)',
 symbol: 'Tied Bunch of Roots / Elephant Goad',
 animal: 'Male Dog',
 gana: 'Rakshasa',
 nadi: 'Adi',
 yoni: 'Dog',
 nature: 'Sharp & Dreadful (Tikshna)',
 characteristics: 'Roots out pretense, deep investigator, transformative truth-seeker, unyielding focus.',
 career: 'Philosophy, deep research, detective, medicine, microbiology, spiritual asceticism.',
 marriage: 'Seeks profound soul connection; detached from superficial social norms.',
 compatibility: ['Purva Ashadha', 'Uttara Ashadha', 'Magha', 'Ashwini']
 },
 'Purva Ashadha': {
 name: 'Purva Ashadha',
 ruler: 'Venus',
 deity: 'Apas (Water Deities)',
 symbol: 'Winnowing Basket / Fan',
 animal: 'Male Monkey',
 gana: 'Manushya',
 nadi: 'Madhya',
 yoni: 'Monkey',
 nature: 'Fierce & Severe (Ugra)',
 characteristics: 'Invincible spirit, proud, purifying orator, emotional depth, inspiring optimism.',
 career: 'Public speaking, marine biology, law, motivational training, philosophy, poetry.',
 marriage: 'Brings immense enthusiasm into family life; proud and supportive companion.',
 compatibility: ['Mula', 'Uttara Ashadha', 'Bharani', 'Revati']
 },
 'Uttara Ashadha': {
 name: 'Uttara Ashadha',
 ruler: 'Sun',
 deity: 'Vishwadevas (Universal Gods)',
 symbol: 'Elephant’s Tusk / Small Bed',
 animal: 'Female Mongoose',
 gana: 'Manushya',
 nadi: 'Antya',
 yoni: 'Mongoose',
 nature: 'Fixed & Steady (Sthira)',
 characteristics: 'Unstoppable victory, righteous conduct, patient leader, abiding integrity, modest.',
 career: 'Government policy, judiciary, military strategy, construction, global leadership.',
 marriage: 'Fulfill domestic commitments with unwavering duty and spiritual dignity.',
 compatibility: ['Mula', 'Purva Ashadha', 'Shravana', 'Krittika']
 },
 Shravana: {
 name: 'Shravana',
 ruler: 'Moon',
 deity: 'Vishnu (Preserver of Cosmos)',
 symbol: 'Three Footprints / Ear',
 animal: 'Female Monkey',
 gana: 'Deva',
 nadi: 'Antya',
 yoni: 'Monkey',
 nature: 'Movable & Renewable (Chara)',
 characteristics: 'Active listener, preserver of oral traditions, scholarly, intuitive wisdom, compassionate.',
 career: 'Teaching, audio engineering, linguistics, journalism, counseling, administration, music.',
 marriage: 'Attentive and sympathetic spouse; values clear listening and intellectual sharing.',
 compatibility: ['Uttara Ashadha', 'Dhanishta', 'Rohini', 'Pushya']
 },
 Dhanishta: {
 name: 'Dhanishta',
 ruler: 'Mars',
 deity: 'Eight Vasus (Deities of Abundance)',
 symbol: 'Drum (Dhamru) / Flute',
 animal: 'Female Lion',
 gana: 'Rakshasa',
 nadi: 'Madhya',
 yoni: 'Lion',
 nature: 'Movable & Renewable (Chara)',
 characteristics: 'Rhythmic, musical talent, wealthy, influential, loves performing arts, generous.',
 career: 'Music production, dance, real estate development, financial banking, sports management.',
 marriage: 'Enjoys vibrant marital life; values financial independence and social prestige.',
 compatibility: ['Shravana', 'Shatabhisha', 'Mrigashira', 'Chitra']
 },
 Shatabhisha: {
 name: 'Shatabhisha',
 ruler: 'Rahu',
 deity: 'Varuna (God of Cosmic Waters & Healing)',
 symbol: 'Empty Circle / 100 Physicians',
 animal: 'Female Horse',
 gana: 'Rakshasa',
 nadi: 'Adi',
 yoni: 'Horse',
 nature: 'Movable & Renewable (Chara)',
 characteristics: 'Mystical healer, secretive, visionary scientist, philosophical, boundary-pushing thinker.',
 career: 'Pharmacology, astronomy, nuclear physics, alternative medicine, radar technology.',
 marriage: 'Needs space and emotional independence; loyal after trust is established.',
 compatibility: ['Dhanishta', 'Purva Bhadrapada', 'Ardra', 'Swati']
 },
 'Purva Bhadrapada': {
 name: 'Purva Bhadrapada',
 ruler: 'Jupiter',
 deity: 'Aja Ekapada (One-Footed Serpent / Fire Dragon)',
 symbol: 'Swords / Front Part of Funeral Cot',
 animal: 'Male Lion',
 gana: 'Manushya',
 nadi: 'Adi',
 yoni: 'Lion',
 nature: 'Fierce & Severe (Ugra)',
 characteristics: 'Passionate reformer, intense spiritual seeker, radical honesty, eccentric genius.',
 career: 'Astrology, occult studies, transformation coaching, radical research, philosophy.',
 marriage: 'Profoundly devoted to spouse; values deep spiritual and intellectual alignment.',
 compatibility: ['Shatabhisha', 'Uttara Bhadrapada', 'Punarvasu', 'Vishakha']
 },
 'Uttara Bhadrapada': {
 name: 'Uttara Bhadrapada',
 ruler: 'Saturn',
 deity: 'Ahirbudhnya (Serpent of the Deeps)',
 symbol: 'Twin Fishes / Back of Funeral Cot',
 animal: 'Female Cow',
 gana: 'Manushya',
 nadi: 'Madhya',
 yoni: 'Cow',
 nature: 'Fixed & Steady (Sthira)',
 characteristics: 'Deep meditation, patient, wisdom of ocean depths, compassionate guardian, serene.',
 career: 'Psychiatry, charitable foundations, deep water exploration, yoga, philosophy, writing.',
 marriage: 'Provides immense emotional calm and unconditional support to domestic life.',
 compatibility: ['Purva Bhadrapada', 'Revati', 'Pushya', 'Anuradha']
 },
 Revati: {
 name: 'Revati',
 ruler: 'Mercury',
 deity: 'Pushan (Nurturer & Protector of Travelers)',
 symbol: 'Pair of Fish / Drum',
 animal: 'Female Elephant',
 gana: 'Deva',
 nadi: 'Antya',
 yoni: 'Elephant',
 nature: 'Soft & Tender (Mridu)',
 characteristics: 'Compassionate, imaginative, unconditional love, guiding light for lost souls, prosperous.',
 career: 'Travel agency, veterinary science, artistic illustration, foster care, music, literature.',
 marriage: 'Extremely devoted, romantic, and gentle partner; creates a loving, spiritual home.',
 compatibility: ['Uttara Bhadrapada', 'Ashwini', 'Bharani', 'Ashlesha']
 }
};

export function getNakshatraDetail(name: string): NakshatraDetail {
 return NAKSHATRA_DATASET[name] || NAKSHATRA_DATASET['Ashwini'];
}
